<?php

namespace LKE\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $limit
     * @param int $page
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryListUser($limit, $page)
    {
        return $this->createQueryBuilder('u')
                    ->setMaxResults($limit)
                    ->setFirstResult($limit * ($page - 1));
    }
}
