<?php

namespace LKE\BlogBundle\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function getQb(QueryBuilder $qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('c') : $qb;
    }

    /**
     * @param $slug
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function bySlug($slug, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
            ->andWhere("c.slug = :slug")
            ->setParameter("slug", $slug);

        return $qb;
    }

    /**
     * @param $slug
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findBySlug($slug)
    {
        $qb = $this->bySlug($slug);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
