<?php

namespace LKE\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private function getQb($qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('c') : $qb;
    }

    private function bySlug($slug, $qb = null)
    {
        $qb = $this->getQb($qb)
            ->andWhere("c.slug = :slug")
            ->setParameter("slug", $slug);

        return $qb;
    }

    public function findBySlug($slug)
    {
        $qb = $this->bySlug($slug);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
