<?php

namespace LKE\BlogBundle\Repository;

use LKE\BlogBundle\Entity\Post;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    private function getQb($qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('c') : $qb;
    }

    private function byPost(Post $post, $qb = null)
    {
        $qb = $this->getQb($qb)
            ->andWhere("c.post = :post")
            ->setParameter("post", $post);

        return $qb;
    }

    public function countComment(Post $post)
    {
        $qb = $this->byPost($post)
                    ->select("COUNT(c)");

        return $qb->getQuery()->getSingleScalarResult();
    }
}
