<?php

namespace LKE\BlogBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use LKE\BlogBundle\Entity\Post;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function getQb(QueryBuilder $qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('c') : $qb;
    }

    /**
     * @param Post $post
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function byPost(Post $post, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
            ->andWhere("c.post = :post")
            ->setParameter("post", $post);

        return $qb;
    }

    /**
     * @param Post $post
     * @return int
     */
    public function countComment(Post $post)
    {
        $qb = $this->byPost($post)
                    ->select("COUNT(c)");

        return $qb->getQuery()->getSingleScalarResult();
    }
}
