<?php

namespace LKE\BlogBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use LKE\BlogBundle\Entity\Category;
use LKE\BlogBundle\Entity\Tag;
use LKE\UserBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function getQb(QueryBuilder $qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('p') : $qb;
    }

    /**
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function qbForPublishedPost(QueryBuilder $qb = null)
    {
        $now = new \DateTime();

        $qb = $this->getQb($qb)
                    ->where('p.publishedAt < :now')
                    ->setParameter('now', $now)
                    ->orderBy('p.publishedAt', 'DESC');

        return $qb;
    }

    /**
     * @param $slug
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function bySlug($slug, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
                    ->andWhere("p.slug = :slug")
                    ->setParameter("slug", $slug);

        return $qb;
    }

    /**
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function previewPost(QueryBuilder $qb = null)
    {
        $qb = $this->qbForPublishedPost($qb)
                    ->leftJoin('p.image', 'i')
                    ->leftJoin('p.category', 'c')
                    ->addSelect('i')
                    ->addSelect('c');

        return $qb;
    }

    /**
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function fullPost(QueryBuilder $qb = null)
    {
        $qb = $this->previewPost($qb)
                    ->leftJoin('p.tags', 't')
                    ->leftJoin('p.comments', 'co')
                    ->addSelect('t')
                    ->addSelect('co');

        return $qb;
    }

    /**
     * @param Tag $tag
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function byTag(Tag $tag, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
                    ->leftJoin("p.tags", 't')
                    ->andWhere("t = :tag")
                    ->setParameter("tag", $tag);

        return $qb;
    }

    /**
     * @param Category $category
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function byCategory(Category $category, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
            ->andWhere("c = :category")
            ->setParameter("category", $category);

        return $qb;
    }

    /**
     * @param User $author
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function byAuthor(User $author, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
            ->leftJoin("p.author", "a")
            ->andWhere("a = :author")
            ->setParameter("author", $author);

        return $qb;
    }

    /**
     * @param int $limit
     * @param int $page
     * @param QueryBuilder|null $qb
     * @return QueryBuilder
     */
    private function pagine($limit, $page, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
                ->setMaxResults($limit)
                ->setFirstResult(($page - 1) * $limit);

        return $qb;
    }

    /**
     * @param int $limit
     * @return array
     */
    public function findLastPublishedPost($limit = 5)
    {
        $qb = $this->queryListPublishedPost($limit, 1);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param int $limit
     * @param int $page
     * @return QueryBuilder
     */
    public function queryListPublishedPost($limit, $page)
    {
        $qb = $this->qbForPublishedPost();
        $qb = $this->previewPost($qb);
        $qb = $this->pagine($limit, $page, $qb);

        return $qb;
    }

    /**
     * @param $slug
     * @return \LKE|BlogBundle\Entity\Post|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findFullBySlug($slug)
    {
        $qb = $this->fullPost();
        $qb = $this->bySlug($slug, $qb);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param string $slug
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findBySlug($slug)
    {
        $qb = $this->bySlug($slug);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param Tag $tag
     * @return array
     */
    public function findPreviewByTag(Tag $tag)
    {
        $qb = $this->previewPost();
        $qb = $this->byTag($tag, $qb);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Category $category
     * @return array
     */
    public function findPreviewByCategory(Category $category)
    {
        $qb = $this->previewPost();
        $qb = $this->byCategory($category, $qb);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Category $category
     * @return int
     */
    public function countPostPerCategory(Category $category)
    {
        $qb = $this->qbForPublishedPost()
                    ->leftJoin('p.category', 'c');
        $qb = $this->byCategory($category, $qb);
        $qb->select("COUNT(p)");

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param User $author
     * @param int $limit
     * @param int $page
     * @return QueryBuilder
     */
    public function queryListPostPreviewByAuthor(User $author, $limit, $page)
    {
        $qb = $this->previewPost();
        $qb = $this->byAuthor($author, $qb);
        $qb = $this->pagine($limit, $page, $qb);

        return $qb;
    }
}
