<?php

namespace LKE\BlogBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param QueryBuilder $qb
     * @return QueryBuilder|null
     */
    private function getQb(QueryBuilder $qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('t') : $qb;
    }

    /**
     * @param string $slug
     * @param QueryBuilder|null $qb
     * @return QueryBuilder|null
     */
    private function bySlug($slug, QueryBuilder $qb = null)
    {
        $qb = $this->getQb($qb)
                    ->andWhere("t.slug = :slug")
                    ->setParameter("slug", $slug);

        return $qb;
    }

    /**
     * @param string $slug
     * @return \LKE\BlogBundle\Entity\Tag|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findBySlug($slug)
    {
        $qb = $this->bySlug($slug);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
