<?php

namespace LKE\BlogBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    private function getQb($qb = null)
    {
        return is_null($qb) ? $this->createQueryBuilder('t') : $qb;
    }

    private function bySlug($slug, $qb = null)
    {
        $qb = $this->getQb($qb)
                    ->andWhere("t.slug = :slug")
                    ->setParameter("slug", $slug);

        return $qb;
    }

    public function findBySlug($slug)
    {
        $qb = $this->bySlug($slug);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
